[theme]
primaryColor = "#4CAF50"
backgroundColor = "#c0c0c0"
secondaryBackgroundColor = "#f8f8ff"
textColor = "#000000"
font = "sans serif"




26574767 , 19740984                Total = 46357857